version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=N8NSuperAdminUser
      - N8N_BASIC_AUTH_PASSWORD=MegaSecretPassword1*
    volumes:
      - ./n8n_data:/home/node/.n8n
